# Generated by Django 3.2.18 on 2023-06-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230610_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatrooms',
            old_name='is_Presenter',
            new_name='is_presenter',
        ),
    ]
